name: Release Rust Crate

on:
  push:
    branches:
      - main
    tags:
      - "v*" # only trigger publish step when a version tag is pushed

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release
        working-directory: skillet

      - name: Run tests
        run: cargo test --all
        working-directory: skillet

      - name: Publish to crates.io
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: skillet
