name: Release Rust Crate

on:
  push:
    tags:
      - "v*" # only runs when a tag starting with v is pushed

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get full history to validate tag ancestry

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Verify tag commit is on main
        run: |
          TAG_COMMIT=$(git rev-parse HEAD)
          if git merge-base --is-ancestor $TAG_COMMIT origin/main; then
            echo "✅ Tag commit is on main."
          else
            echo "❌ Tag commit is NOT on main. Aborting."
            exit 1
          fi

      - name: Build
        run: cargo build --release
        working-directory: skillet

      - name: Run tests
        run: cargo test --all
        working-directory: skillet

      - name: Publish to crates.io
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: skillet
