name: Update CLI Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write # needed to push to branch & open PR
  pull-requests: write # needed to open PR

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build current code
        run: cargo build --release
        working-directory: skillet

      - name: Generate CLI docs
        run: |
          mkdir -p docs
          ./skillet/target/release/skillet --markdown-help > docs/cli.md

      - name: Set up Python (for pre-commit)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit on docs
        run: pre-commit run --files docs/cli.md || true

      - name: Create PR with updated CLI docs
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update CLI docs"
          title: "Update CLI docs"
          body: "Automated update of CLI docs after push to main."
          branch: update/cli-docs
          author: "bpgould <38466458+bpgould@users.noreply.github.com>"
          delete-branch: true
          token: ${{ secrets.DOCS_TOKEN }}
